import {
  spfOne,
  spfTwo,
  spfThree,
  spfFour,
  bestSellerOne,
  bestSellerTwo,
  bestSellerThree,
  bestSellerFour,
  newArrOne,
  newArrTwo,
  newArrThree,
  newArrFour,
  newArrFive,
  wm4,
  wm3,
  wm2,
  wm1,
  sofa1,
  sofa4,
  sofa3,
  sofa2,
  bed4,
  bed3,
  bed2,
  bed1,
} from "../assets/images/index";

// =================== NavBarList Start here ====================
export const navBarList = [
  {
    _id: 1001,
    title: "Home",
    link: "/",
  },
  {
    _id: 1002,
    title: "Shop",
    link: "/shop",
  },
  {
    _id: 1003,
    title: "About",
    link: "/about",
  },
  {
    _id: 1004,
    title: "Contact",
    link: "contact",
  },
];
// =================== NavBarList End here ======================
// =================== Special Offer data Start here ============
export const SplOfferData = [
  {
    _id: "201",
    img: spfOne,
    productName: "SAMSUNG 236 L Frost Free Double Door 3 Star Convertible Refrigerator with Digital Inverter with Display  (Elegant Inox, RT28C3733S8/HL)",
    price: "26990.00",
    color: "Elegant Inox",
    badge: true,
    des: "You can stock up on your weekly groceries and easily store them in the Samsung Refrigerator. Moreover, you can even store additional groceries and other food items in this refrigerator by converting the freezer into a fridge. With this refrigerator's Power Cool feature, you can cool groceries or drinks quickly with a simple touch. Also, it has a Power Freeze feature that allows you to freeze food or make ice with the touch of a button.",
  },
  {
    _id: "202",
    img: spfTwo,
    productName: "Whirlpool 235 L Frost Free Double Door 2 Star Refrigerator  (Magnum Steel, IF INV ELT DF278 Magnum Steel(2S)TL)",
    price: "22990.00",
    color: "Magnum Steel",
    badge: true,
    des: "The Whirlpool 235 L Frost Free Double Door Convertible Refrigerator has a special Cool Pad that keeps the freezer cold during power outages for up to 17 hours, preventing ice from melting and other items from spoiling. This refrigerator's Intellisense Inverter Technology adjusts cooling to internal load, minimises energy consumption, and enables stable operation even in conditions of significant voltage fluctuation between 160 and 260 V. In order to maintain balanced air and maximum freshness in the vegetable compartment, the Honeycomb Crisper Cover condenses the evaporated moisture from the food.",
  },
  {
    _id: "203",
    img: spfThree,
    productName: "LG 242 L Frost Free Double Door 3 Star Refrigerator with Smart Inverter  (Shiny Steel, GL-I292RPZX)",
    price: "25990.00",
    color: "Shiny Steel",
    badge: true,
    des: "You can enjoy chilled drinks and popsicles during summer by keeping them stocked up in the LG 242 L Frost-free Double-door Refrigerator. Its Smart Inverter Compressor is designed to deliver energy-efficient performance, thus keeping a check on your electricity bills. Also, this refrigerator’s Door Cooling+ feature keeps the food items fresh and drinks chilled while rendering uniform rapid cooling. Moreover, its Multi Air Flow system controls the temperature levels to keep the contents fresh.",
  },
  {
    _id: "204",
    img: spfFour,
    productName: "Haier 190 L Direct Cool Single Door 4 Star Refrigerator with Base Drawer  (MARINE PEONY, HED-204MFB-P)",
    price: "15990.00",
    color: "MARINE PEONY",
    badge: true,
    
    des: "Bring home a new refrigerator that keeps your food fresh and has enhanced storage capacity. The Haier single door refrigerator has a clean back that protects the internal components and allows you to clean it easily. With the external handle, you can open and close the door more conveniently. Thanks to its large vegetable tray that allows you to store all your vegetables in a single space and keeps them fresh for a long time. It has an LED lamp that helps to find your food easily and saves energy by up to 75%. With customisable temperature control, you can set the temperature according to your need. The toughened glass shelves make it easy to store heavy food items. It also features an antibacterial gasket that protects your food from bacteria and fungi to keep them fresh for a long period of time.",
  },
];
// =================== Special Offer data End here ==============

// =================== PaginationItems Start here ===============

export const paginationItems = [
  {
    _id: 1001,
    img: newArrOne,
    productName: "SAMSUNG 80 cm (32 Inch) HD Ready LED Smart Tizen TV 2022 Edition with Bezel-free Design  (UA32T4380AKXXL)",
    price: "14990.00",
    color: "Black",
    badge: true,
    des: "Installation: The TV table stand is not included in the box with this model. Customers may ask for the table top stand or wall mount which will be provided to the customer at the time of installation. Please directly call Samsung support (please visit the brand website for toll-free numbers) and provide the product's model name as well as the seller's details mentioned on the invoice to make the request. Description With this Samsung TV, every image on the screen comes to life, giving you a home theatre experience. With the HD visual quality of this TV, you can enjoy vibrant movie scenes. Additionally, HDR increases the screen's brightness and brings out the subtleties of the material. Moreover, the Contrast Enhancer on this TV improves contrast and offers superb image quality with increased depth.",
  },
  {
    _id: 1002,
    img:newArrTwo,
    productName: "Mi X Series 125 cm (50 inch) Ultra HD (4K) LED Smart Android TV 2022 Edition with 4K Dolby Vision | HDR10 | HLG | Dolby Audio | DTS: Virtual X | DTS-HD |Vivid Picture Engine",
    price: "31999.00",
    color: "Gray",
    badge: true,
    des: "With this Xiaomi TV that breathes life into your entertainment, you bring home the real entertainer and always keep one step ahead of the entertainment curve. The stunning bezel-less design of this TV elevates your viewing experience to a whole new level. Furthermore, you can hear every note thanks to Dolby Audio and 30 W of power from the speakers. The Quad-core A55 CPU also enables this TV to function amazingly well, mesmerising you with its effectiveness.",
  },
  {
    _id: 1003,
    img: newArrThree,
    productName: "SONY Bravia 108 cm (43 inch) Ultra HD (4K) LED Smart Google TV 2022 Edition  (KD - 43X74K)",
    price: "37990.00",
    color: "Black",
    badge: true,
    des: "Experience a jitter-free and colour-enriched visual experience with the Sony TV which is designed to take your entertainment to an elevated level. This TV is driven by the X1 processor which helps in reducing the noise and boosts the visual quality. Furthermore, the impressive 4K X-Reality PRO of this TV amplifies the visuals and enables you to appreciate up to 4K picture clarity. Additionally, with Motionflow XR 100 sported in this TV, there is no stopping for your entertainment, and you can flawlessly enjoy stutter-free visuals no matter how graphically rich the content is.",
  },
  {
    _id: 1004,
    img: newArrFour,
    productName: "realme 126 cm (50 inch) Ultra HD (4K) LED Smart Android TV with Handsfree Voice Search and Dolby Vision & Atmos  (RMV2005)",
    price: "26999.00",
    color: "White",
    badge: true,
    des: "The realme 4K TV is equipped with innovative features that will give you an immersive cinematic experience as soon as you play all your favourite movies. With a 4K UHD MediaTek Processor, you can enjoy a smooth visual experience without any glitches so that nothing interrupts your movie time. When you’re tired of manually controlling the TV and other AloT devices, you can make use of the Hands-free Voice Control feature (via Google Assistant) to do so. And, powered by Google, this TV brings you a variety of content through the Google Play Store.",
  },
  {
    _id: 1005,
    img: newArrFive,
    productName: "OnePlus U1S 164 cm (65 inch) Ultra HD (4K) LED Smart Android TV with Far field and Dolby Audio  (65UC1A00)",
    price: "47999.00",
    color: "Mixed",
    badge: true,
    des: "The OnePlus 50UC1A00 TV is your one home entertainment appliance for immersive, unlimited, and exciting audio-visual delight. This television features a 4K UHD Display for detailed, clear, and immersive visuals, Dynaudio sound offers well-balanced audio, and OnePlus Connect 2.0 to connect your smartphone to this TV.",
  },
  {
    _id: 1006,
    img: bestSellerOne,
    productName: "Classic Essentials Pack of 32 Stainless Steel Peacock Lazer Design Stainless Steel Heavy Gauge Dinner Set Shagun|Bartan Set Dinner Set  (Silver)",
    price: "1099.00",
    color: "Silver",
    badge: false,
    des: "Featuring a set of 32 stainless steel Dinner Set including Full Plates, Half Plates, Curry Bowls Large, Chatni Katori, Desert Dish, Glass, Desert Spoon, Baby Spoon, Fork, Baby Fork, and Fork, the Classic Essentials Dinner set is ideal serving a scrumptious meal for people with ease. Featuring a highly attractive design motif, this lunch set will surely impress your lunch and dinner guests while providing a great canvas to showcase your delicious food. Apart from your own use, you can also give this lunch set to your loved ones as a perfect gifting option on special occasions or festivals. Made from thicker gauge stainless steel, the 32-piece Classic Essentials Dinner set is highly durable and can withstand the rigours of daily use with ease. Its strong and sturdy construction makes this set an ideal solution for both special occasions as well as everyday meals. Furthermore, all plates, spoons and bowls in this set are rust-proof and hygienic, preventing contamination of your food. The individual pieces in this Dinner set can be nested together and this makes them ideal to stack up and store away when not being used, saving valuable kitchen space. Thanks to its sturdy construction, you can easily clean this Dinner set with a simple detergent solution and retain its shiny looks for a long time.",
  },
  {
    _id: 1007,
    img: bestSellerTwo,
    productName: "Larah by Borosil Pack of 34 Opalware Galaxy Fauna Crockey Set for Dining & Gifting, Plate & Bowl Dinner Set  (White, Green, Microwave Safe)",
    price: "1999.00",
    color: "White",
    badge: true,
    des: "Blending beauty with functionality, the Borosil Larah 34-piece opal ware dinner set is an elegant way to serve dinner to your family or guests. You can set out a variety of dishes with the help of this dinner set, as it includes six full plates, six quarter plated, 12 mini bowls, two serving bowls with two lids, and one six spoons. Borosil, a well-established company, has drawn inspiration from fashion and home decor trends to create a dinner set that teams aesthetic appeal with practical use. Moreover, each lightweight yet durable piece is designed to handle rough use without getting scratched or chipped.  Food-safe Material  Designed using opal ware, a non-porous material, the Borosil Larah 34-piece opal ware dinner set does not absorb food particles, thereby curbing the growth of bacteria. This ensures that each piece of this dinnerware is completely food-safe and hygienic. And, as opal ware is free from bone ash, this dinner set is 100% vegetarian. Durable Design   You don’t have to bring out this dinner set only when you have guests at home. Resistant to breaking, chipping, and scratches, this durable dinner set is ideal for daily use as well. So, you can use this dinner set on a regular basis and create a fine dining experience at home. Worry-free Maintenance Made from fully tempered, toughened glass, each piece is durable yet light in weight, which helps ensure hassle-free use and cleaning. Also, the convenient stackable design allows you to stow away this dinner set in your crockery cabinet, without taking up too much space. Dishwasher- and Microwave-safe  You can effortlessly warm up food or reheat leftovers using this dinner set, as it is microwave-safe. It is also dishwasher-safe, which makes cleaning seem like an effortless chore.  Usage Instructions While cleaning this dinner set, use a soft sponge instead of a scouring pad. Also, you cannot use this opal ware dinner set on the flame.",
  },
  {
    _id: 1008,
    img: bestSellerThree,
    productName: "Abode SmartBuy Pack of 61 Stainless Steel Dinner Set  (Silver)",
    price: "2499.00",
    color: "Silver",
    badge: false,
    des: "You can create a complete utensil collection with the Flipkart SmartBuy Stainless Steel Dinner Set (Pack of 61). This dinner set contains different glasses, spoons, dinner plates, serving bowls, forks, a jug, a rice spoon, a rice plate, and more, thereby making it suitable for your kitchen. Made from high-grade stainless steel, this dinner set provides long-lasting performance. Also, it is safe for the freezer, so you can store your favourite frozen desserts or dishes with ease.",
  },
  {
    _id: 1009,
    img: bestSellerFour,
    productName: "Servewell Pack of 5 Melamin Kids Set - Peppa Pig Dinner Set  (Multicolor)",
    price: "693.00",
    color: "Multicolor",
    badge: true,
    des: "Make your little ones smile with their favourite character mealtime set. This set will surely bring adventure to the kids tables and the bold character art will make every meal fun for them.",
  },
  {
    _id: 1010,
    img: spfOne,
    productName: "SAMSUNG 236 L Frost Free Double Door 3 Star Convertible Refrigerator with Digital Inverter with Display  (Elegant Inox, RT28C3733S8/HL)",
    price: "26990.00",
    color: "Elegant Inox",
    badge: true,
    des: "You can stock up on your weekly groceries and easily store them in the Samsung Refrigerator. Moreover, you can even store additional groceries and other food items in this refrigerator by converting the freezer into a fridge. With this refrigerator's Power Cool feature, you can cool groceries or drinks quickly with a simple touch. Also, it has a Power Freeze feature that allows you to freeze food or make ice with the touch of a button.",
  },
  {
    _id: 1011,
    img: spfTwo,
    productName: "Whirlpool 235 L Frost Free Double Door 2 Star Refrigerator  (Magnum Steel, IF INV ELT DF278 Magnum Steel(2S)TL)",
    price: "22990.00",
    color: "Magnum Steel",
    badge: true,
    des: "The Whirlpool 235 L Frost Free Double Door Convertible Refrigerator has a special Cool Pad that keeps the freezer cold during power outages for up to 17 hours, preventing ice from melting and other items from spoiling. This refrigerator's Intellisense Inverter Technology adjusts cooling to internal load, minimises energy consumption, and enables stable operation even in conditions of significant voltage fluctuation between 160 and 260 V. In order to maintain balanced air and maximum freshness in the vegetable compartment, the Honeycomb Crisper Cover condenses the evaporated moisture from the food.",
  },
  {
    _id: 1012,
    img: spfThree,
    productName: "LG 242 L Frost Free Double Door 3 Star Refrigerator with Smart Inverter  (Shiny Steel, GL-I292RPZX)",
    price: "25990.00",
    color: "Shiny Steel",
    badge: false,
    des: "You can enjoy chilled drinks and popsicles during summer by keeping them stocked up in the LG 242 L Frost-free Double-door Refrigerator. Its Smart Inverter Compressor is designed to deliver energy-efficient performance, thus keeping a check on your electricity bills. Also, this refrigerator’s Door Cooling+ feature keeps the food items fresh and drinks chilled while rendering uniform rapid cooling. Moreover, its Multi Air Flow system controls the temperature levels to keep the contents fresh.",
  },
  {
    _id: 1013,
    img: spfFour,
    productName: "Haier 190 L Direct Cool Single Door 4 Star Refrigerator with Base Drawer  (MARINE PEONY, HED-204MFB-P)",
    price: "15990.00",
    color: "MARINE PEONY",
    badge: false,
    des: "Bring home a new refrigerator that keeps your food fresh and has enhanced storage capacity. The Haier single door refrigerator has a clean back that protects the internal components and allows you to clean it easily. With the external handle, you can open and close the door more conveniently. Thanks to its large vegetable tray that allows you to store all your vegetables in a single space and keeps them fresh for a long time. It has an LED lamp that helps to find your food easily and saves energy by up to 75%. With customisable temperature control, you can set the temperature according to your need. The toughened glass shelves make it easy to store heavy food items. It also features an antibacterial gasket that protects your food from bacteria and fungi to keep them fresh for a long period of time.",
  },

  {
    _id: 1014,
    img: bed1,
    productName: "Sofani Solid Sheesham Wood King Size Poster Bed For Bedroom/ Hotel/ Kids Room | Solid Wood King Bed  (Finish Color - Teak Finish, Delivery Condition - DIY(Do-It-Yourself))",
    price: "39999.00",
    color: "Teak Finish",
    badge: true,
    des: "This Sheesham Wood Poster Bed is an exquisite and timeless piece of furniture that seamlessly blends traditional craftsmanship with contemporary design. Crafted from high-quality Sheesham wood, also known as Indian Rosewood, this bed exudes a warm and rich natural grain, creating a luxurious and inviting ambiance in any bedroom. The standout feature of this poster bed is its stately four-poster design, which adds an element of grandeur to the overall aesthetic. The tall, sturdy posters are intricately carved, showcasing the artisan's attention to detail and commitment to quality. The bed's headboard and footboard also often feature elegant carvings or detailing that contribute to its overall charm.",
  },
  {
    _id: 1015,
    img: bed2,
    productName: "Divine Arts Sheesham Wood Queen Size Double Bed with Storage Box for Living Room, Bed Room Solid Wood Queen Box Bed  (Finish Color - Honey Brown 2, Delivery Condition - DIY(Do-It-Yourself))",
    price: "30000.00",
    color: "Honey Brown",
    badge: false,
    des: " Divine Arts is an International brand that has been working last 10 Years Globally and our Item quality is perfect we believe in quality work and craftsmanship. Our goal is to provide you a fashionable, well-design yet affordable dining, giving you an ideal solution to decorate your home. Furinno is the manufacturer of all types of furniture like solid wood dining table sets, bookshelf, bedside tables, coffee tables, wooden nesting tables, dressing tables, study tables, computer desks, beds, sofas, sofa beds, furniture wardrobe, wooden sideboard, bar cabinet, shoe rack, wall shelf, kitchen cabinets, stools, etc.",
  },
  {
    _id: 1016,
    img: bed3,
    productName: "Delite Kom Cherry Engineered Wood Single Bed  (Finish Color - Acacia Dark, Delivery Condition - Knock Down)",
    price: "9999.00",
    color: "Acacia Dark",
    badge: true,
    des: "Important Note   Cancellation NOT allowed for this product after 24 hrs of order booking.",
  },
  {
    _id: 1017,
    img: bed4,
    productName: "Bharat Lifestyle Amsterdam Engineered Wood Queen Bed  (Finish Color - Brown & White, Delivery Condition - Knock Down)",
    price: "9999.00",
    color: " Brown & White",
    badge: false,
    des: "Bharat Lifestyle Amsterdam Queen Size Brown Color Bed Will Give A Complete Look And Class To Your Bedroom. This Bed Is From Contemporary Range Of Furniture's. It has combination of adorable color and the beautiful paneling with matte finishing.",
  },
  {
    _id: 1018,
    img: sofa1,
    productName: "Taskwood Furniture Solid Sheesham Wood Five Seater Sofa Set For Living Room, Office, Café Fabric 3 + 1 + 1 Sofa Set  (Honey Teak Design 1, DIY(Do-It-Yourself))",
    price: "34999.00",
    color: "Honey Teak Design",
    badge: true,
    des: "TASKWOOD FURNITURES Presents-Elegantly styled, this Sofa set makes for a great addition to your home. The set has an extremely modern and contemporary look that helps you set up a stylish Sofa space in your home. Easily seating adults while still leaving you enough space on, it is just what you need for a beautiful Living room. Ergonomically designed Sofa ensure comfort as you enjoy a leisurely meal with your family and friends. Seat has Enough space to Sitting comfortably.",
  },
  {
    _id: 1019,
    img: sofa2,
    productName: "Bharat Lifestyle Tulip Fabric 3 + 1 + 1 Sofa Set  (Black, DIY(Do-It-Yourself))",
    price: "17999.00",
    color: "Black",
    badge: true,
    des: "This sofa set is a clear all-rounder when it comes to using it for any weather, be it summer or winter, thanks to its fabric upholstery which offers long-lasting comfort.",
  },
  {
    _id: 1020,
    img: sofa3,
    productName: "M.k.decor Leather 3 + 2 + 2 + 1 Sofa Set  (White, Pre-assembled)",
    price: "24808.00",
    color: "White",
    badge: true,
    des: "This unique product serves the purpose which comes in various ranges & varieties and hence fulfills the need of all.",
  },
  {
    _id: 1021,
    img: sofa4,
    productName: "HMG Fabric 3 + 1 + 1 Sofa Set  (Dark & Light Grey, DIY(Do-It-Yourself))",
    price: "18999.00",
    color: "Dark & Light Grey",
    badge: true,
    des: "The color of the product may vary slightly from the picture displayed on your screen: this is due to lighting, pixel quality and color settings. Please check the product dimensions to ensure the product will fit in the desired location. Also, check if the product will fit through the entrance(s) and door(s) of the premises. And if there is no elevator in a multi-storey building, we might be unable to deliver the item to your doorstep. Please expect an unevenness of up to 5 mm in the product due to differences in surfaces and floor levels. Flipkart, or the Seller delivering the product, will not take up any type of civil work, such as drilling holes in the wall to mount the product. The product will only be assembled if carpentry-assembly is required. In case the product appears to lack shine, wiping the surface with a cloth will help clear the surface of dust particles.",
  },
  {
    _id: 1022,
    img: wm1,
    productName: "Godrej 6.5 kg 5 Star With I-Wash Technology Washing Machine Fully Automatic Top Load Grey  (WTEON 650 AP 5.0 GPGR)",
    price: "12990.00",
    color: "Grey",
    badge: true,
    des: "This Godrej washing machine makes life easy with its built-in Soak technology that soaks the clothes before beginning the wash cycle. Its Auto Resume technology restores the operation in case of power failure between wash cycles. It has about 5 wash programs to choose from to suit your needs. The Auto Balance system of this washing machine detects the imbalance and distributes the load to prevent vibration. The 6 ridges on the pulsator offer a powerful wash by dissolving the detergent more efficiently.",
  },
  {
    _id: 1023,
    img: wm2,
    productName: "LG 7 kg 5 Star with Wind Jet Dry, Collar Scrubber and Rust Free Plastic Base Semi Automatic Top Load Washing Machine Grey, White  (P7020NGAZ)",
    price: "11490.00",
    color: "Grey, White ",
    badge: true,
    des: "5 Star Rating Plastic Body Normal Pulsator Rat Away Technology 3 Wash Programs Wind Jet Dry.Wash 7Kg and Spin 5.5Kg, 5 Star, Rust Free Body, Wind Jet Dry, Color : Dark Gray .",
  },
  {
    _id: 1024,
    img: wm3,
    productName: "realme TechLife 7.5 kg 5 Star Rating Fabric Safe Wash Fully Automatic Top Load Washing Machine Grey  (RMFA75A5G)",
    price: "11990.00",
    color: "Grey  ",
    badge: true,
    des: "The improved scrubbing and whirling movement makes this washing machine highly functional. It has a fuzzy logic feature that picks up the wash cycle time and ensures an effective wash. This machine features a number of wash programs such as Rapid wash, Spin only, Air dry, Tub clean etc. among others. ‘Delay wash’ is a salient feature of this washing machine where you can schedule wash at your convenience by activating the ‘Delay’ button. The machine has a 5-star BEE rating and saves energy.",
  },
  {
    _id: 1025,
    img: wm4,
    productName: "MOTOROLA 10 kg 5 star rating Semi Automatic Top Load Washing Machine Black  (MTSA1005NNNDB)",
    price: "10990.00",
    color: "Black ",
    badge: true,
    des: "The Motorola 10 kg Washing Machine has your back with its Quick Dry feature. Equipped with a large air dry lid and a powerful spin of 1350 RPM, it dries your clothes up to 15% fast.",
  },
  {
    _id: 1026,
    img: spfThree,
    productName: "Headphones",
    price: "25.00",
    color: "Mixed",
    badge: true,
    des: "",
  },
  {
    _id: 1027,
    img: spfFour,
    productName: "Sun glasses",
    price: "220.00",
    color: "Black",
    badge: true,
    des: "",
  },
  {
    _id: 1028,
    img: bestSellerOne,
    productName: "Flower Base",
    price: "35.00",
    color: "Blank and White",
    badge: true,
    des: "",
  },
  {
    _id: 1029,
    img: bestSellerTwo,
    productName: "New Backpack",
    price: "180.00",
    color: "Gray",
    badge: false,
    des: "",
  },
  {
    _id: 1030,
    img: bestSellerThree,
    productName: "Household materials",
    price: "25.00",
    color: "Mixed",
    badge: true,
    des: "",
  },
  {
    _id: 1031,
    img: bestSellerFour,
    productName: "Travel Bag",
    price: "220.00",
    color: "Black",
    badge: false,
    des: "",
  },
  {
    _id: 1032,
    img: newArrOne,
    productName: "Round Table Clock",
    price: "44.00",
    color: "Black",
    badge: true,
    des: "",
  },
  {
    _id: 1033,
    img: newArrTwo,
    productName: "Smart Watch",
    price: "250.00",
    color: "Black",
    badge: true,
    des: "",
  },
  {
    _id: 1034,
    img: newArrThree,
    productName: "cloth Basket",
    price: "80.00",
    color: "Mixed",
    badge: true,
    des: "",
  },
  {
    _id: 1035,
    img: newArrFour,
    productName: "Funny toys for babies",
    price: "60.00",
    color: "Mixed",
    badge: false,
    des: "",
  },
  {
    _id: 1036,
    img: newArrTwo,
    productName: "Funny toys for babies",
    price: "60.00",
    color: "Mixed",
    badge: false,
    des: "",
  },
  {
    _id: 1037,
    img: newArrFour,
    productName: "Funny toys for babies",
    price: "60.00",
    color: "Mixed",
    badge: false,
    des: "",
  },
  {
    _id: 1038,
    img: newArrTwo,
    productName: "Smart Watch",
    price: "250.00",
    color: "Black",
    badge: true,
    des: "",
  },
  {
    _id: 1039,
    img: bestSellerFour,
    productName: "Travel Bag",
    price: "220.00",
    color: "Black",
    badge: false,
    des: "",
  },
  {
    _id: 1040,
    img: newArrOne,
    productName: "Round Table Clock",
    price: "44.00",
    color: "Black",
    badge: true,
    des: "",
  },
  {
    _id: 1041,
    img: newArrTwo,
    productName: "Smart Watch",
    price: "250.00",
    color: "Black",
    badge: true,
    des: "",
  },
  {
    _id: 1042,
    img: newArrThree,
    productName: "cloth Basket",
    price: "80.00",
    color: "Mixed",
    badge: true,
    des: "",
  },
  {
    _id: 1043,
    img: spfThree,
    productName: "Headphones",
    price: "25.00",
    color: "Mixed",
    badge: true,
    des: "",
  },
  {
    _id: 1044,
    img: spfFour,
    productName: "Sun glasses",
    price: "220.00",
    color: "Black",
    badge: true,
    des: "",
  },
  {
    _id: 1045,
    img: bestSellerOne,
    productName: "Flower Base",
    price: "35.00",
    color: "Blank and White",
    badge: true,
    des: "",
  },
  {
    _id: 1046,
    img: spfOne,
    productName: "Cap for Boys",
    price: "35.00",
    color: "Blank and White",
    badge: true,
    des: "",
  },
];
// =================== PaginationItems End here =================
